"use client";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { Check, Copy, Plus, TerminalSquare, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
type Token = { id: string; name: string; tokenPrefix: string; createdAt: string; lastUsedAt: string | null };
export function CliTokenManager({ tokens }: { tokens: Token[] }) { const router = useRouter(); const [created, setCreated] = useState<string | null>(null); const [copied, setCopied] = useState(false); async function create(fd: FormData) { const r = await fetch("/api/cli-tokens", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name: fd.get("name") }) }); const data = await r.json(); if (r.ok) { setCreated(data.token); router.refresh(); } } async function revoke(id: string) { await fetch("/api/cli-tokens", { method: "DELETE", headers: { "content-type": "application/json" }, body: JSON.stringify({ id }) }); router.refresh(); } return <div><div className="mb-8 flex justify-between"><div><p className="text-sm text-muted-foreground">Access</p><h1 className="text-2xl font-semibold">CLI Tokens</h1></div><Dialog onOpenChange={(open) => !open && setCreated(null)}><DialogTrigger asChild><Button><Plus />New token</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>{created ? "Copy your token" : "Create CLI token"}</DialogTitle><DialogDescription>{created ? "Shown once. Store it securely." : "Identify the device or pipeline."}</DialogDescription></DialogHeader>{created ? <div className="flex gap-2 rounded-md border p-3"><code className="min-w-0 flex-1 break-all text-xs text-primary">{created}</code><Button size="icon-sm" variant="ghost" onClick={async () => { await navigator.clipboard.writeText(created); setCopied(true); }} >{copied ? <Check /> : <Copy />}</Button></div> : <form action={create} className="space-y-4"><Label>Name</Label><Input name="name" placeholder="Personal Laptop" required /><Button className="w-full">Generate</Button></form>}</DialogContent></Dialog></div><div className="overflow-hidden rounded-lg border">{tokens.length ? tokens.map((t) => <div key={t.id} className="flex items-center justify-between border-b p-4 last:border-0"><div className="flex gap-3"><TerminalSquare className="size-5" /><div><p className="text-sm font-medium">{t.name}</p><p className="font-mono text-xs text-muted-foreground">{t.tokenPrefix}</p></div></div><div className="flex items-center gap-3 text-xs text-muted-foreground"><span>{t.lastUsedAt ? "Used " + new Date(t.lastUsedAt).toLocaleDateString("pt-BR") : "Never used"}</span><Button size="icon-sm" variant="ghost" onClick={() => revoke(t.id)}><Trash2 /></Button></div></div>) : <p className="py-20 text-center text-sm text-muted-foreground">No CLI tokens.</p>}</div></div>; }
